LR: 0.001
weight_decay: 0.01
scheduler_gamma: 0.8
betas: [.07, .99]
step_size: 1
swa_start: .5
log_epoch: 10
save_model: True
transform_data: False
warm_start: True
loss_landscape: False
output_images: False
model_type: Segmentation
patience: 150
is_tuning: False
max_epochs: 150
exp_name: train-segmentation
init_task: False
log_dir: ./logs
dataset_params:
  data_path: ./data
  train_batch_size: 4
  val_batch_size: 4
  pin_memory: False
  split: .7
  data_patches: 1000
  single_example: False
  # These values are taken from a sampling of data
  mu: 274662906.04691434
  var: 49527137064.739006
  noise_level: 0.
model_params:
  in_channels: 1
  channel_sz: 64